### PR TITLE
chore: bump mongodb to v6

### PR DESCRIPTION
**Pull request by timonmasberg**
Ran into peer dependency issues.  You can review the changes here: https://github.com/mongodb/node-mongodb-native/releases/tag/v6.0.0. It seems to me that no breaking change is relevant for the internals of this library.

### CODE REVIEW

**Comment by jrh-exacta** [comment]
Is anyone working on this?  It would be great to have :)

**Comment by timonmasberg** [comment]
> Is anyone working on this?  It would be great to have :)
> 
> 

The maintainer just has to merge this PR, but he seems quite busy atm

**Comment by puschkin** [comment]
Hello @mycodeself  I would be grateful was well if this was merged :)

**Comment by mycodeself** [comment]
Hey @timonmasberg thanks for your contribution! Sorry for the delay, but yes I'm little bit busy atm.

Would you mind bumping the version of the mongo image used in the circleci tests to make sure it works correctly with mongo version 6? 

line 9 in file `.circleci/config.yml`

thanks!

**Comment by timonmasberg** [comment]
> Hey @timonmasberg thanks for your contribution! Sorry for the delay, but yes I'm little bit busy atm.
> 
> Would you mind bumping the version of the mongo image used in the circleci tests to make sure it works correctly with mongo version 6?
> 
> line 9 in file `.circleci/config.yml`
> 
> thanks!

ah missed that, thanks

**Review by mycodeself — APPROVED** [review]

**Pull request merged**
